### ISSUE TITLE
Refactor API to make it useful across applications.

### ISSUE THREAD

**Issue by conorhastings** [socialtables/text-cheers#6]

**Comment by rickyvetter** [comment]
Is this referring to the API used in `/send`? I was just looking at this to see if chrome-cheers could use it. I don't think I want to format my requests like the same way twilio is formatting stuff. This would be cool to have!

**Comment by conorhastings** [comment]
Yeah, the twilio formatting is really bad, going to either have a flag or alternate endpoint for requests from non twilio locations

**Comment by conorhastings** [comment]
Added /cheer/:token endpoint for easier cheers sending through api

**Comment by rickyvetter** [comment]
@conorhastings niice. Looks good.
